[package]
name = "asm6502"
version = "0.1.0"
authors = ["W. Brian Gourlie <bgourlie@gmail.com>"]
description = "A basic 6502 assembler"
license = "MIT"
repository = "https://github.com/bgourlie/asm6502"

[badges]
travis-ci = { repository = "https://github.com/bgourlie/asm6502", branch = "master" }

[dependencies]
nom = "^2.0"